### ISSUE TITLE
Conduct Accessibility Review

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/cs-wp-in-the-headlines#6]
to be assigned to Rob when element is in a presentable place

**Comment by Sporkyy** [comment]
With a little searching some automated tools https://github.com/paypal/AATT
And services https://tenon.io
That can be integrated into testing infrastructures via APIs

**Comment by Sporkyy** [comment]
This was deprioritized when the timetable accelerated. Reopen if necessary.
