### ISSUE TITLE
Convert styling in .less to .scss

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/cs-wp-in-the-headlines#7]

**Comment by Sporkyy** [comment]
Here's the old files. I don't think it's worth creating another repo for it. That seems wasteful.

[news-article-in-the-headlines.zip](https://github.com/merceruniversity/cs-wp-in-the-headlines/files/1812949/news-article-in-the-headlines.zip)

**Comment by cinakur** [comment]
- [ ] look at [image slider scss](https://github.com/InteractiveDesignAndDevelopment/image-index-slider/tree/master/scss)
- [ ] convert less to scss
- [ ] check with todd on general set up and stuff

**Comment by cinakur** [comment]
#14
